[package]
name = "fields-metadata"
version = "0.1.0"
edition = "2024"
description = "Internal proc-macros for tentacli"
repository = "https://github.com/tench-rt/tentacli"

[lib]
name = "fields_metadata"
path = "src/lib.rs"
proc-macro = true

[dependencies]
syn = { version = "2.0.100", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"