[package]
name = "tentacli"
version = "15.0.0"
edition = "2024"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
description = "Framework for building extensible network protocol clients via modular plugins."
readme = "README.md"
keywords = [
    "protocol",
    "network",
    "framework",
    "plugin",
    "wow"
]
license-file = "LICENSE"
repository = "https://github.com/tench-rt/tentacli"

[workspace]
members = [
    ".",
    "src/client/macros/packet",
    "src/client/macros/fields_metadata",
    "src/client/macros/bitflags_extras",
]

[dependencies]
anymap2 = "0.13.0"
async-broadcast = "0.7.1"
async-event-emitter = { version = "0.1.5", optional = true }
async-trait = "0.1.88"
anyhow = "1.0.97"
binrw = "0.14.1"
bitflags = { version = "2.9.4", optional = true }
bitflags-extras = { path = "src/client/macros/bitflags_extras" }
byteorder = "1.5.0"
cfg-if = "1.0.0"
chrono = "0.4"
colored = { version = "3.0.0", optional = true }
criterion = "0.5.1"
crossterm = { version = "0.28.1", features = ["default", "event-stream", "serde"], optional = true }
dirs-next = "2.0.0"
fields-metadata = { path = "src/client/macros/fields_metadata" }
flate2 = { version = "1.0.24", optional = true }
futures = "0.3.31"
hmac-sha = { version = "0.6.1", optional = true }
inventory = "0.3"
num-bigint = { version = "0.4.6", optional = true }
num_enum = "0.7.4"
rand = { version = "0.9.0", optional = true }
packet = { path = "src/client/macros/packet" }
ratatui = { version = "0.29.0", features = ["crossterm"], optional = true }
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
sha-1 = { version = "0.9.8", optional = true }
tokio = { version = "1", features = ["sync", "net", "io-util", "macros", "time", "rt-multi-thread", "io-std"] }
tokio-util = { version = "0.7.15", features = ["compat"] }
toml = "0.8.20"

[dev-dependencies]
tempfile = "3"
rusty-hook = "0.11.2"

[features]
default = ["wow-wotlk", "tui"]
default-dbg = ["wow-wotlk", "dbg-ui"]
tui = ["crossterm", "ratatui", "async-event-emitter"]
dbg-ui = ["colored"]
wow-wotlk = ["bitflags", "flate2", "sha-1", "hmac-sha", "rand", "num-bigint"]
