[package]
name = "tentacli-traits"
version = "8.1.0"
edition = "2021"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
description = "Traits and types for tentacli and related projects"
keywords = [
    "idewave", "tentacli", "tentacli-traits", "traits"
]
license-file = "../../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-broadcast = "0.7.0"
async-trait = "0.1.57"
bitflags = "2.5.0"
byteorder = "1.4.3"
dotenv = "0.15.0"
serde = { version = "1.0.197", features = ["derive"] }
tentacli-crypto = "0.1.0"
tentacli-utils = "2.1.0"
thiserror = "1.0"
tokio = { version = "1", features = ["sync", "net", "io-util", "macros", "time", "rt-multi-thread"] }
yaml-rust = "0.4.5"
tempdir = "0.3.7"

[dev-dependencies]
tempdir = "0.3.7"

[lib]
name = "tentacli_traits"
path = "src/lib.rs"
