[package]
name = "tentacli-crypto"
version = "1.0.0"
edition = "2021"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
description = "Crypto functions for tentacli"
keywords = [
    "idewave", "tentacli", "tentacli-crypto", "cryptography"
]
license-file = "../../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac-sha = "0.6.1"
num-bigint = "0.4.3"
rand = "0.9.0"
sha-1 = "0.9.8"

[lib]
name = "tentacli_crypto"
path = "src/lib.rs"
