[package]
name = "tentacli-formatters"
version = "0.1.0"
edition = "2021"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
description = "Formatters for output"
keywords = [
    "idewave", "tentacli-formatters", "tentacli"
]
license-file = "../../../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"

[lib]
name = "tentacli_formatters"
path = "src/lib.rs"
