[package]
name = "tentacli-utils"
version = "1.1.0"
edition = "2021"
authors = ["Sergio Ivanuzzo <sergio.ivanuzzo@gmail.com>"]
description = "Utils for tentacli and related projects"
keywords = [
    "idewave", "tentacli", "tentacli-utils", "utils"
]
license-file = "../../../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
byteorder = "1.4.3"
flate2 = "1.0.24"
rand = "0.8.5"

[dev-dependencies]
tempdir = "0.3.7"

[lib]
name = "tentacli_utils"
path = "src/lib.rs"
