name: Rust

on:
  push:
    branches: ["main", "master", "primary", "dev"]
  pull_request:
    branches: ["main", "master", "primary"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
